### PR TITLE
Test

### PR DESCRIPTION
**Pull request by ianjfrosst**
Want to make sure I can pull request properly.

### CODE REVIEW

**Comment by Morgrimm** [comment]
Yep, you can - EZ PZ

**Comment by RangerMauve** [comment]
If you become a collaborator then you can all just work in the same repo

**Comment by ianjfrosst** [comment]
Yes, but Remi is the project ~~overlord~~ manager. He and Dorian are the only ones with direct push access. He has decreed that anyone else must make a pull request to contribute.

**Comment by RangerMauve** [comment]
PFFFFFFFFFFFFFFFFFFFFFFT

Just make sure people don't commit directly to master.

Each feature should be developed in its own branch, then when it's ready, merge it into master

**Comment by ianjfrosst** [comment]
Oh, I know. Like I said, Remi is the project manager. His choice, not mine.

**Comment by RangerMauve** [comment]
Remi should take this into consideration. It'll make things a bit less confusing and prep you guys for working in an actual environment better.

**Comment by dustan1** [comment]
Wait, who's this person? I'm Dorian, by the way.

**Comment by RangerMauve** [comment]
Oh, that's Ian Frost from Bell.

**Comment by dustan1** [comment]
How about you? Have I met you before?

**Comment by RangerMauve** [comment]
Probably not, considering I graduated in '13

**Comment by dustan1** [comment]
Well then, will you be contributing to this project, or just watching?

**Comment by RangerMauve** [comment]
Probably just watching. I'm kinda interested to see what you guys are up to.

**Comment by dustan1** [comment]
Not much right now. Getting people to work on small school projects is already hard...

**Comment by Morgrimm** [comment]
When I get some time I will be moving to seperate branches - my reason for restricting direct access was that the majority of people working on the project are new to programming and VCS. What I'll do is create separate branches per feature and restrict merging to master without my say-so.

**Comment by ianjfrosst** [comment]
*Frosst

**Pull request closed without merging**
